In [1]:
import numpy as np

In [2]:
a=np.array(15)
a

array(15)

In [4]:
x=np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ndim(x)


2

In [8]:
a=np.arange(15,40)     
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [9]:
b=a*2                 
b

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78])

In [10]:
c=a+b                 
c

array([ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
        84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117])

In [11]:
1/c*c    

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:

c>50                  

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [14]:
c[9]  

72

In [15]:
d=c[c>78]             #10
d

array([ 81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117])

In [16]:
np.sqrt(d)

array([ 9.        ,  9.16515139,  9.32737905,  9.48683298,  9.64365076,
        9.79795897,  9.94987437, 10.09950494, 10.24695077, 10.39230485,
       10.53565375, 10.67707825, 10.81665383])

In [18]:
np.power(5,2)

25

In [19]:
np.exp(d) 

array([1.50609731e+35, 3.02507732e+36, 6.07603023e+37, 1.22040329e+39,
       2.45124554e+40, 4.92345829e+41, 9.88903032e+42, 1.98626484e+44,
       3.98951957e+45, 8.01316426e+46, 1.60948707e+48, 3.23274119e+49,
       6.49313426e+50])

In [21]:
x=np.ones((6,6))        
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
x[1:-1,1:-1]=0          
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
x[1:,1:]+=2            
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 3.],
       [1., 2., 2., 2., 2., 3.],
       [1., 2., 2., 2., 2., 3.],
       [1., 2., 2., 2., 2., 3.],
       [1., 3., 3., 3., 3., 3.]])

In [25]:
z=np.random.random((2,2))    
z

array([[0.47538746, 0.03357899],
       [0.90658896, 0.57407836]])

In [26]:
z.min()  

0.033578991375626366

In [27]:
z.max()

0.9065889646211648

In [28]:
z.mean()

0.49740844451393224

In [29]:
z[1:2]**2  

array([[0.82190355, 0.32956597]])

In [30]:
a=np.array([8,0,8,6,4])
a

array([8, 0, 8, 6, 4])

In [31]:
a[::-1]    #Prints in reverse form

array([4, 6, 8, 0, 8])

In [32]:
a = np.arange(-4,8).reshape(4, 3)   #Creates an array from the range and then converts to 4 x 3
a

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [33]:
a[::2]  #parses the first two rows

array([[-4, -3, -2],
       [ 2,  3,  4]])

In [36]:
a[-1,1]=1     
a

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  1,  1]])

In [37]:
np.linspace(1,2,5) 

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
y=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
y[0]=0                 
y

array([[[ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
c=np.arange(0,12).reshape(4,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
c[1:3,2:3]  #works only if the second number is bigger than the first

array([[5],
       [8]])

In [48]:
u=[-3,-2,0,1,2,4,6,7,9]

In [49]:
v=[-4,5,6,8,9,8,9,2,-2]

In [50]:
w=np.intersect1d(u,v)    #displays common elements in 1D
w

array([-2,  2,  6,  9])

In [51]:
np.where(w)  

(array([0, 1, 2, 3], dtype=int64),)

In [52]:
np.setdiff1d(u,v)

array([-3,  0,  1,  4,  7])

In [53]:
k=np.concatenate((u,v))   
k

array([-3, -2,  0,  1,  2,  4,  6,  7,  9, -4,  5,  6,  8,  9,  8,  9,  2,
       -2])

In [54]:
k[k%2==1] 

array([-3,  1,  7,  9,  5,  9,  9])

In [55]:
k[k%2==0]   

array([-2,  0,  2,  4,  6, -4,  6,  8,  8,  2, -2])

In [56]:
np.where(k%2==1,-1,k)

array([-1, -2,  0, -1,  2,  4,  6, -1, -1, -4, -1,  6,  8, -1,  8, -1,  2,
       -2])

In [58]:
j=np.arange(9).reshape(3,3) #reshape index's product must be equal to the arrange number
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
j[[0,2,1,],:] #rearranges the array to the input index

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [63]:
j[[0],:]+2 

array([[2, 3, 4]])

In [64]:
m=np.arange(20)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
np.set_printoptions(threshold=8)

In [66]:
np.where(m<5,4,np.where(m>15,3,m))

array([4, 4, 4, ..., 3, 3, 3])

In [67]:
np.random.seed(50)

In [69]:
a=np.random.uniform(1,9)            
a

2.8246648355946897

In [70]:
np.cos(a)

-0.9501973427072258

In [71]:
a=np.arange(3)
b=np.arange(1,4)                     
c=np.arange(0,2,5)

In [72]:
d=np.array([a,b,c])                 
d

<ipython-input-72-0aa9923f9c06>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d=np.array([a,b,c])


array([array([0, 1, 2]), array([1, 2, 3]), array([0])], dtype=object)

In [73]:
x=np.zeros((7,7))
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
x+=np.arange(7)                    
x

array([[0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       ...,
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.]])

In [77]:
y=np.random.random(4)             
y.sort()
y

array([0.71409271, 0.73268761, 0.92593317, 0.93801522])

In [79]:
z=np.arange(10)                     
np.add.reduce(z)

45

In [80]:
a=np.random.random(4)              
a[a.argmax()]=0
a

array([0.46174768, 0.        , 0.40642024, 0.68320577])

In [82]:
a= [0,2,4,6,8]                     
b= [1,3,5,7,9]
c= np.bincount(a,b)
c

array([1., 0., 3., ..., 7., 0., 9.])

In [83]:
a= np.arange(16).reshape(4,4)      
a[[0,1]] = a[[1,0]]
a

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
z=np.random.randint(0,20,30)        
print(np.bincount(z).argmax())

0
